service:
  name: openspace-backend
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    PROD_DB_URI: ${env:PROD_DB_URI}
    PROD_DB_USER: ${env:PROD_DB_USER}
    PROD_DB_PASSWD: ${env:PROD_DB_PASSWD}
    PROD_DB_NAME: ${env:PROD_DB_NAME}
    DB_PORT: ${env:DB_PORT}
  profile: open-space-serverless-admin

functions:
  getSessions:
    handler: handler.getSessions
    events:
      - http:
          method: get
          path: api/sessions

  addSession:
    handler: handler.addASession
    events:
      - http:
          method: post
          path: api/sessions

  deleteSession:
    handler: handler.deleteASession
    events:
      - http:
          method: delete
          path: api/sessions/{id}

  editSession:
    handler: handler.editASession
          method: put
          path: api/sessions/{id}