version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  aws-cli-setup:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: open-space-serverless-admin
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY

  build:
    docker:
      - image: circleci/12.16.1-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      # run tests!
      - run:
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Deploy application
          command: sls deploy --stage pre