version: 2
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      # run tests!
      - run:
          name: Run tests with coverage
          command: npm test --coverage

      - run:
          name: Setup AWS Credentials
          command: |
            serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY --profile open-space-serverless-admin

      - run:
          name: Deploy application
          command: sls deploy --stage pre --region $AWS_REGION